install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin

build_script:
  - cd VisualRacing 
  - qmake VisualRacing.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" 
  - mingw32-make

test_script:
  - dir
#  - powershell -file "../appveyor/test_script.ps1"
- pushd VRTest/debug
- dir
- echo "Running Tests"
- tst_vrtest
- tst_vrtest -xunitxml > tests.xml
- dir
- type tests.xml
- popd

on_finish:
  - powershell -file "../appveyor/upload_script.ps1"