environment:
  matrix:
    - QT: C:\Qt\5.7\msvc2015_64
      PLATFORM: amd64
      COMPILER: msvc
      VSVER: 14
 
build_script:
  - call "appveyor/build_windows.cmd"

#test_script:
#  - cd VisualRacing/VRTest
#  - qmake VRTest.pro
#  - mingw32-make
#  - dir
#  - echo "Running Tests"
#  - VRTest.exe -xunitxml > tests.xml

#on_finish:
#  - ps: (New-Object System.Net.Webclient).UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))