install:
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
 
build_script:
  - cd VisualRacing 
  - qmake VisualRAcing.pro -r -spec win32-g++
  - mingw32-make
  - dir

#test_script:
#  - cd VisualRacing/VRTest
#  - qmake VRTest.pro
#  - mingw32-make
#  - dir
#  - echo "Running Tests"
#  - VRTest.exe -xunitxml > tests.xml

#on_finish:
#  - ps: (New-Object System.Net.Webclient).UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))