install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
 
build_script:
   - qmake VisualRacing/VRMain/VRMain.pro

test_script:
  - cd VisualRacing/VRTest
  - qmake VRTest.pro
  - dir
  - echo "Running Tests"
  - VRTest.exe -xunitxml > tests.xml

on_finish:
  - ps: (New-Object System.Net.Webclient).UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))