install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin

build_script:
  - cd VisualRacing 
  - qmake VisualRacing.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" 
  - mingw32-make

test_script:
  - pushd VRTest/debug
  - dir
  - echo "Running Tests"
  - tst_vrtest.exe
  - tst_vrtest.exe -xunitxml > tests.xml
  - dir
  - type tests.xml

on_finish:
  - popd
  - call "appveyor/upload_script.ps"