install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;

build_script:
  - cd VisualRacing 
  - qmake VisualRacing.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" 
  - mingw32-make

after_build:
  - windeployqt --qmldir VRMain VRMain/debug/VRMain.exe
  - echo "Cleaning up directory"
  - cd VRMain
  - rm debug/*.o
  - rm debug/*.cpp
  - rm debug/*.h
  - rm debug/D3Dcompiler_47.dll
  - rm debug/libEGLd.dll
  - rm debug/libGLESV2d.dll
  - rm debug/opengl32sw.dll
  - rmdir /s /q "debug/platforminputcontexts"
  - rmdir /s /q "debug/bearer"
  - rmdir /s /q "debug/iconengines"
  - rmdir /s /q "debug/printsupport"
  - rmdir /s /q "debug/qmltooling"
  - rmdir /s /q "debug/QtGraphicalEffects"
  - rmdir /s /q "debug/QtQml"
  - rmdir /s /q "debug/translations"
  - rename debug Release
  - cd ../


test_script:
  - powershell -file "../appveyor/test_script.ps1"

on_finish:
  - powershell -file "../appveyor/upload_script.ps1"

artifacts:
  - path: VisualRacing/VRMain/Release
    type: zip