install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;

build_script:
  - cd VisualRacing 
  - qmake VisualRacing.pro -spec win32-g++ "CONFIG+=release" 
  - mingw32-make

after_build:
  - windeployqt --qmldir VRMain VRMain/release/VRMain.exe
  - echo "Cleaning up directory"
  - cd VRMain
  - rm release/*.o
  - rm release/*.cpp
  - rm release/*.h
  - rm release/D3Dcompiler_47.dll
  - rm release/opengl32sw.dll
  - rmdir /s /q "release/platforminputcontexts"
  - rmdir /s /q "release/bearer"
  - rmdir /s /q "release/iconengines"
  - rmdir /s /q "release/printsupport"
  - rmdir /s /q "release/qmltooling"
  - rmdir /s /q "release/QtGraphicalEffects"
  - rmdir /s /q "release/QtQml"
  - rmdir /s /q "release/translations"
  - rename release VisualRacing
  - cd ../


test_script:
  - powershell -file "../appveyor/test_script.ps1"

on_finish:
  - powershell -file "../appveyor/upload_script.ps1"

artifacts:
  - path: "VisualRacing/VRMain/VisualRacing"
    type: zip

deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: iFpWSofle5jrfjvrGkYVRxAW6Ykb8mzVgsbCZAIo+1PjzxoksLvDwXfFPwcqFKgM
  artifact: "VisualRacing/VRMain/VisualRacing.zip"
  prerelease: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only